import {
  sepolia,
  zkSyncSepoliaTestnet,
  polygonMumbai,
  bscTestnet,
  arbitrum,
  avalanche,
  aurora,
  base,
  blast,
  boba,
  bsc,
  celo,
  cronos,
  mainnet,
  evmos,
  fantom,
  fuse,
  gnosis,
  harmonyOne,
  linea,
  mantle,
  metis,
  mode,
  moonriver,
  moonbeam,
  okc,
  opBNB,
  optimism,
  polygon,
  polygonZkEvm,
  rootstock,
  scroll,
  zkSync,
} from 'viem/chains';
import { cookieStorage, createConfig, createStorage, http } from 'wagmi';

// velo, velas ??

export default createConfig({
  chains: [
    sepolia,
    zkSyncSepoliaTestnet,
    polygonMumbai,
    bscTestnet,
    mainnet,
    zkSync,
    polygon,
    bsc,
    celo,
    optimism,
    avalanche,
    harmonyOne,
    fantom,
    moonriver,
    cronos,
    aurora,
    evmos,
    rootstock,
    fuse,
    scroll,
    mode,
    moonbeam,
    linea,
    metis,
    opBNB,
    base,
    blast,
    boba,
    gnosis,
    mantle,
    okc,
    polygonZkEvm,
    arbitrum
  ],
  ssr: true,
  storage: createStorage({
    storage: cookieStorage
  }),
  transports: {
    [sepolia.id]: http(),
    [bscTestnet.id]: http(),
    [zkSyncSepoliaTestnet.id]: http(),
    [polygonMumbai.id]: http(),
    [mainnet.id]: http(),
    [zkSync.id]: http(),
    [polygon.id]: http(),
    [bsc.id]: http(),
    [celo.id]: http(),
    [optimism.id]: http(),
    [avalanche.id]: http(),
    [harmonyOne.id]: http(),
    [fantom.id]: http(),
    [moonriver.id]: http(),
    [cronos.id]: http(),
    [aurora.id]: http(),
    [evmos.id]: http(),
    [rootstock.id]: http(),
    [fuse.id]: http(),
    [scroll.id]: http(),
    [mode.id]: http(),
    [moonbeam.id]: http(),
    [linea.id]: http(),
    [metis.id]: http(),
    [opBNB.id]: http(),
    [base.id]: http(),
    [blast.id]: http(),
    [boba.id]: http(),
    [gnosis.id]: http(),
    [mantle.id]: http(),
    [okc.id]: http(),
    [polygonZkEvm.id]: http(),
    [arbitrum.id]: http()
  }
});
